// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw6;

#nullable disable

namespace cw6.Migrations
{
    [DbContext(typeof(s25236Database))]
    [Migration("20240527195818_AddedMedikamentTable")]
    partial class AddedMedikamentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cw6.Medikament", b =>
                {
                    b.Property<int>("IdMedikament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedikament"));

                    b.HasKey("IdMedikament");

                    b.ToTable("Medikaments");
                });
#pragma warning restore 612, 618
        }
    }
}
